image: alpine:latest

test:
  stage: test
  script: python -m pytest --cov=. tests/
  only:
  - merge_requests

pages:
  stage: deploy
  script:
  - echo 'Hello CI'
  artifacts:
    paths:
    - public
  only:
  - master
