image: python:3.6

test:
  stage: test
  script:
    # - apt-get update -qy
    # - apt-get install -y python3-pip
    - pip3 install -r requirements.txt
    - cd ~/harvest/datajson/
    - python -m pytest tests/
    - cd ~/harvest/csw/
    - python -m pytest tests/
    - cd ~/libs/
    - python -m pytest tests/
  only:
  - merge_requests

pages:
  stage: deploy
  script:
  - echo 'Hello GitLab CI'
  artifacts:
    paths:
    - public
  only:
  - master
