image: python:3.6

test:
  stage: test
  script:
    # - apt-get update -qy
    # - apt-get install -y python3-pip
    - echo '***************************'
    - echo 'Instaling reqs'
    - pip3 install -r requirements.txt
    - echo '***************************'
    - echo 'path'
    - pwd

    - echo '***************************'
    - echo 'Test data.json'
    - cd harvest/datajson/
    - python -m pytest tests/

    - echo '***************************'
    - echo 'Test csw'
    - cd ../../harvest/csw/
    - python -m pytest tests/
    - echo '***************************'
    - echo 'Test package'
    - cd ~/libs/
    - python -m pytest tests/

  only:
  - merge_requests

pages:
  stage: deploy
  script:
  - echo 'Hello GitLab CI'
  artifacts:
    paths:
    - public
  only:
  - master
