image: python:3.6

test:
  stage: test
  script:
    # - apt-get update -qy
    # - apt-get install -y python3-pip
    - echo '***************************'
    - echo 'Installing reqs'
    - pip3 install -r requirements.txt -r dev-requirements.txt
    - echo '***************************'
    - pwd

    - DEVHOME=$(pwd)
    - echo '***************************'
    - echo 'Test data.json'
    - cd "$DEVHOME/harvest/datajson/"
    - pwd
    - python -m pytest tests/

    - echo '***************************'
    - echo 'Test csw'
    - cd "$DEVHOME/harvest/csw/"
    - pwd
    - python -m pytest tests/

    - echo '***************************'
    - echo 'Checking dependencies for vulnerabilities'
    - cd "$DEVHOME"
    - safety check --full-report

    - echo '***************************'
    - echo 'Static security scan'
    - bandit -r .

  only:
  - merge_requests

pages:
  stage: deploy
  script:
  - echo 'Hello GitLab CI'
  artifacts:
    paths:
    - public
  only:
  - master
