image: alpine:latest

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3.6 python3-pip
    - pip3 install -r requirements.txt
    - python -m pytest --cov=. tests/
  only:
  - merge_requests

pages:
  stage: deploy
  script:
  - echo 'Hello CI'
  artifacts:
    paths:
    - public
  only:
  - master
