version: '3.2'

services:
    airflow_db:
        container_name: postgres
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        build: .
        restart: always
        command: webserver
        depends_on:
            - airflow_db
            - ckan
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - SQLALCHEMY_URL=postgres://ckan:ckan@ckan_db/ckan
            # CKAN instance to write harvested packages
            - CKAN_API_KEY=READ_FROM_DB
            - CKAN_BASE_URL=http://ckan:5000
            - CKAN_VALID_USER_ID=admin
            - HARVESTER_APP_PATH=/app
            - AIRFLOW__CORE__DAGS_FOLDER=/app/automate-tasks/airflow/dags
            - AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=180
            # The amount of parallelism as a setting to the executor. This defines
            # the max number of task instances that should run simultaneously
            # on this airflow installation
            - AIRFLOW__CORE__PARALLELISM=3
            # The number of task instances allowed to run concurrently by the scheduler
            - AIRFLOW__CORE__DAG_CONCURRENCY=2
            # if False all (or limited by other settings) the harvesters will run at start
            - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
        ports:
            - "8081:8080"

    ckan:
        build:
            context: docker-extras/ckan/
            dockerfile: Dockerfile.dev
        env_file:
            - docker-extras/.env
        links:
            - ckan_db
            - solr
            - redis
        ports:
            - "5000:5000"
        volumes:
            - ./src:/srv/app/src_extensions
            - ckan_storage:/var/lib/ckan
        
    ckan_db:
        container_name: ckan_db
        env_file:
            - docker-extras/.env
        build:
            context: docker-extras/postgresql/
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - "5490:5432"
    solr:
        container_name: solr
        build:
            context: docker-extras/solr/
        ports:
            - "8983:8983"
        volumes:
            - solr_data:/opt/solr/server/solr/ckan/data/index
    
    redis:
        container_name: redis
        image: redis:alpine
    
volumes:
    ckan_storage:
    pg_data:
    solr_data: