version: '3.2'

services:
    airflow_db:
        image: postgres:9.6
        expose:
            - "5432"
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        build: .
        restart: always
        depends_on:
            - airflow_db
            - ckan
        environment:
            - POSTGRES_HOST=airflow_db
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - SQLALCHEMY_URL=postgresql://ckan:123456@ckan_db/ckan # ex ckan_db
            # CKAN instance to write harvested packages
            - CKAN_API_KEY=READ_FROM_DB
            - CKAN_BASE_URL=http://ckan:5000
            - CKAN_VALID_USER_ID=admin
            - HARVESTER_APP_PATH=/app
            - AIRFLOW__CORE__DAGS_FOLDER=/app/automate-tasks/airflow/dags
            - AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=180
            # The amount of parallelism as a setting to the executor. This defines
            # the max number of task instances that should run simultaneously
            # on this airflow installation
            - AIRFLOW__CORE__PARALLELISM=3
            # The number of task instances allowed to run concurrently by the scheduler
            - AIRFLOW__CORE__DAG_CONCURRENCY=2
            # if False all (or limited by other settings) the harvesters will run at start
            - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
        ports:
            - "8081:8080"

    ckan:
        image: viderum/ckan-cloud-docker:ckan-latest-datagov-theme
        restart: always
        volumes:
            - ./ckan-conf/:/etc/ckan-conf/
            - ckan-data:/var/lib/ckan
        environment:
            - CKAN_STORAGE_PATH=/var/lib/ckan/data
            - CKAN_K8S_SECRETS=/etc/ckan-conf/secrets/secrets.sh
            - CKAN_K8S_TEMPLATES=/etc/ckan-conf/templates
            - SQLALCHEMY_URL=postgresql://ckan:123456@ckan_db/ckan
        depends_on:
            - ckan_db
            - redis
            - solr
            - datastore-db
        ports:
            - "5000:5000"
        
    ckan_db:
        image: viderum/ckan-cloud-docker:db-latest
        restart: always
        expose:
            - "5432"
        environment: 
            - POSTGRES_PASSWORD=123456
            - POSTGRES_USER=postgres
            - POSTGRES_DB=ckan
        volumes:
            - db:/var/lib/postgresql/data    
        
    datastore-db:
        image: viderum/ckan-cloud-docker:db-latest
        restart: always
        expose:
            - "5432"
        environment: 
            - DATASTORE_PASSWORD=123456
            - DATASTORE_RO_PASSWORD=123456
            - DATASTORE_RO_USER=readonly
            - DATASTORE_PUBLIC_RO_PASSWORD=123456
        volumes:
            - datastore-db:/var/lib/postgresql/data
        
    solr:
        image: viderum/ckan-cloud-docker:solr-latest
        restart: always
        expose:
            - "8983"
    
    redis:
        image: redis:alpine
        restart: always
        expose:
            - "6379"

volumes:
    db:
    datastore-db:
    ckan-data: