name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    - name: Login with Docker
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: echo -n $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      
    - name: Build the Docker image
      run: docker build -t viderum/ckan-ng-harvest:$(date +%s) .
    
    - name: Push the Docker image
      run: docker push viderum/ckan-ng-harvest
  
